name: Release

on:
  release:
    types:
      - published

jobs:
  deploy:
    uses: croct-tech/github-workflows/.github/workflows/general/publish-npm-package.yml@unify-workflows
    with:
      node-version: "23"
      publish-access: "public"
      prepare-script: >-
        cp LICENSE README.md build/ &&
        cd build &&
        find . -type f -path '*/*\.js.map' -exec sed -i -e "s~../src~src~" {} + &&
        sed -i -e "s~\"version\": \"0.0.0-dev\"~\"version\": \"${GITHUB_REF##*/}\"~" package.json &&
        sed -i -e "s~\./build~.~" package.json &&
        sed -i -e "s~./src~.~" package.json
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
